title: <Aadhars-Personal-Website>
description: <This is the personal website of Aadhar Bansal, Built on Github.com>
twitter_username: AADHARBANSAL
github_username: aadhar01
theme: jekyll-theme-minimal
